openapi: 3.0.0
info:
  title: "Categories API"
  version: "1.0.0"
  description: "API documentation for category management"
tags:
  - name: Categories
    description: "API endpoints for managing categories"
paths:
  /api/categories:
    get:
      summary: "Retrieves a list of categories"
      tags:
        - Categories
      responses:
        '200':
          description: "A list of categories"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
    post:
      summary: "Creates a new category"
      tags:
        - Categories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryInput'
      responses:
        '201':
          description: "Category created successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '400':
          description: "Bad request"
  /api/categories/{id}:
    get:
      summary: "Retrieves a single category by ID"
      tags:
        - Categories
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: "The category ID"
      responses:
        '200':
          description: "A single category"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          description: "Category not found"
    put:
      summary: "Updates an existing category"
      tags:
        - Categories
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: "The category ID"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryInput'
      responses:
        '200':
          description: "Category updated successfully"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '400':
          description: "Bad request"
        '404':
          description: "Category not found"
    delete:
      summary: "Deletes a category"
      tags:
        - Categories
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: "The category ID"
      responses:
        '200':
          description: "Category deleted successfully"
        '404':
          description: "Category not found"
components:
  schemas:
    Category:
      type: object
      properties:
        _id:
          type: string
          description: "The auto-generated id of the category"
        name:
          type: string
          description: "The name of the category"
      required:
        - name
    CategoryInput:
      type: object
      properties:
        name:
          type: string
      required:
        - name
